---
- name: Ensure Pip is installed.
  package:
    #name: "{{ pip_package }}"
    name: python-pip
    state: present
  when: ansible_os_family == 'Debian'

- name: Ensure Pipall2 is installed.
  package:
    #name: "{{ pip_package }}"
    name: python2-pip
    state: present
  loop:
    - python27
    - python2-pip
    - python36
    - python3-pip
  when: ansible_os_family == 'RedHat'

- name: Ensure pip_install_packages are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
  with_items: "{{ pip_install_packages }}"
