- name: pull image from registry
  docker_image:
    build:
      path: /home/deploy/
      pull: yes
    name: "{{ registry_host }}:{{ registry_port }}/simple-rest-app_1.0"
    tag: '{{ item }}'
    #pull: yes
    #repository: "{{ registry_host }}:{{ registry_port }}"
    source: pull
    state: present
  loop:
    - 'latest'
    - '{{ build_number }}'