- name: Include vars
  include_vars:
    file: vars/main.yaml

- name: run docker container
  docker_container:
    name:
    image: "{{ registry_host }}:{{ registry_port }}/simple-rest-app_1.0:{{ version }}"
#    command: redis-server --appendonly yes
    state: started
    recreate: yes
    ports:
     - "{{ app_port }}:8085"