- name: run docker container
  docker_container:
    name:
    image: "{{ registry_host }}:{{ registry_port }}/simple-rest-app_{{ version }}"
#    command: redis-server --appendonly yes
    state: running
    recreate: yes
    ports:
     - "{{ app_port }}:8085"