- name: build image
  #become_user: deploy
  docker_image:
    build:
      path: /home/deploy/
      dockerfile: /home/deploy/DockerFile
    name: "simple-rest-app_{{ version }}"
    tag: latest
    push: yes
    repository: "{{ registry_host }}:{{ registry_port }}"
    source: build
    #state: present