- name: build image
  #become_user: deploy
  become: yes
  docker_image:
    build:
      path: /home/deploy/
      dockerfile: /home/deploy/DockerFile
    name: "{{ registry_host }}:{{ registry_port }}/simple-rest-app_1.0:{{ build_number }}"
    tag: latest
    push: yes
    #repository: "{{ registry_host }}:{{ registry_port }}"
    source: build
    #state: present