- name: set up insecure-registry for client
  become: yes
  template:
    src: roles/role_docker_image_build/template/daemon.json
    dest: /etc/docker
    owner: root
    group: root
    mode: '0644'
  notify: restart docker
