- name: Set fact for Debian
  set_fact:
    ca_path: /usr/local/share/ca-certificates
  when: ansible_os_family == "Debian"

- name: Set fact for RedHat
  set_fact:
    ca_path: /etc/pki/ca-trust/source/anchors
  when: ansible_os_family == "RedHat"

- name: copy certificate
  copy:
    src: /home/ubuntu/secret/domain.crt
    dest: '{{ ca_path }}'
#    dest: /usr/local/share/ca-certificates
  notify:
    - 'update trusted ca {{ ansible_os_family }}'
    - 'restart docker'

