- name: copy certificate
  copy:
    src: /home/ubuntu/secret/domain.crt
    dest: '{{ ca_path }}'
#    dest: /usr/local/share/ca-certificates
  notify:
    - update trusted ca {{ ansible_os_family }}
  vars:
#    ca_path: "ca_path_{{ ansible_os_family }}"
    ca_path: /usr/local/share/ca-certificates
    when: "ansible_os_family == 'Debian'"
    ca_path: /etc/pki/ca-trust/source/anchors
    when: "ansible_os_family == 'RedHat'"
