- name: copy certificate
  include_vars:
    file: 'vars/main.yml'
  copy:
    src: /home/ubuntu/secret/domain.crt
    dest: '{{ ca_path[ansible_os_family][ansible_distribution_major_version|int] }}/'
  notify:
    - update trusted ca {{ ansible_os_family }}

