- name: Ensure Pip is installed.
  package:
    name: "{{ item }}"
    state: present
  loop:
#    - python-pip
    - python3-pip
  when: ansible_os_family == 'Debian'

- name: Ensure Pipall2 is installed, RedHat
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python27
    - python2-pip
    - python36
    - python3-pip
  when: ansible_os_family == 'RedHat'

- name: pip install lxml RedHat
  pip:
    name: lxml
    executable: pip3
  when: ansible_os_family == 'RedHat'

- name: pip install lxml Debian
  pip:
    name: lxml
  when: ansible_os_family == 'Debian'