- name: Ensure Pipall2 is installed.
  package:
    #name: "{{ pip_package }}"
    name: "{{ item }}"
    state: present
  loop:
    - python27
    - python2-pip
    - python36
    - python3-pip
  when: ansible_os_family == 'RedHat'