---
- name: Provisioning
  hosts: CI_linux
  become: yes
  vars_files: 'vars/provision.yml'
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-11-jdk
    - role: geerlingguy.docker
    - role: geerlingguy.repo-epel
      when: "ansible_os_family == 'RedHat'"
    - role: geerlingguy.pip
    - role: provision