--- https://stackoverflow.com/questions/37333305/ansible-create-a-user-with-sudo-privileges
- name: Set authorized keys taken from url
  authorized_key:
    user: charlie
    state: present
    key: https://github.com/charlie.keys

- name: Set up authorized keys for the deploy user
  authorized_key: user=deployer key="{{item}}"
  with_file:
    - /home/railsdev/.ssh/id_rsa.pub